name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "skills.html"
      - "skills.json"
      - ".github/workflows/deploy-pages.yml"
  workflow_dispatch:
  workflow_run:
    workflows: ["Update skills data from skills.yaml"]
    types:
      - completed
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare deployment
        run: |
          mkdir -p _site
          cp skills.html _site/index.html
          cp skills.json _site/skills.json
          cp CNAME _site/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
